name: make kernel

on:
  workflow_dispatch:

    inputs:
      KERNEL_SOURCE:
        description: 'Kernel Source'
        required: true
        default: 'https://github.com/OnePlusOSS/android_kernel_oneplus_sm8250'
        
      KERNEL_SOURCE_BRANCH:
        description: 'Branch'
        required: true
        default: 'oneplus/SM8250_R_11.0_9R'
        
      KERNEL_DEFCONFIG:
        description: 'Defconfig'
        required: true
        default: 'vendor/kona-perf_defconfig'

      CLANG_URL:
        description: 'Clang URL'
        required: true
        default: 'https://github.com/ZyCromerZ/Clang/releases/download/14.0.0-20211201-release/Clang-14.0.0-20211201.tar.gz'
       
      KERNEL_CMDLINE:
        description: 'cmdline'
        required: true
        default: 'ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- LLVM=1 LLVM_IAS=1 O=out'
         
      USE_KERNELSU:
        description: 'Use KernelSU'
        required: true
        default: 'false'
        type: boolean

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 100

    - name: Set up ccache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Install dependencies
      run: |
        sudo apt-get update -y 
        sudo apt install gcc-aarch64-linux-gnu -y
        sudo apt install gcc-arm-linux-gnueabi -y
        sudo apt install binutils make python3 libssl-dev build-essential bc  bison flex unzip libssl-dev ca-certificates xz-utils mkbootimg cpio device-tree-compiler git git-lfs -y
        git clone https://codeberg.org/Mandi-Sa/clang --dept=1 -b amd64-kernel-arm
        git clone https://github.com/zhlhlf/AnyKernel3 --depth=1
        rm -rf AnyKernel3/.git
        git clone --depth=1 ${{ github.event.inputs.KERNEL_SOURCE }} -b ${{ github.event.inputs.KERNEL_SOURCE_BRANCH }} android-kernel
            
    - name: GetTime
      id: get_time
      run: |
        echo "TIME=$(TZ=UTC+8 date +%m%d%H%M )" >> $GITHUB_OUTPUT

    - name: Build Kernel
      run: |
       export PATH=$(pwd)/clang/bin/:$PATH
       cd android-kernel       
       export ARCH=arm64
       export SUBARCH=arm64
       make $KERNEL_CMDLINE ${{ github.event.inputs.KERNEL_DEFCONFIG }} CC="ccache clang"
       make $KERNEL_CMDLINE CC="ccache clang" -j$(nproc --all)
       cp out/arch/arm64/boot/Image.gz AnyKernel3
       
    - name: Upload Kernel
      uses: actions/upload-artifact@v3
      with:
        name: Qiuqiu-kernel-${{ steps.get_time.outputs.TIME }}
        path: "AnyKernel3/*"

    - name: Build Kernel-SU
      run: |
        curl -LSs "https://raw.github.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
        export PATH=$(pwd)/clang/bin/:$PATH
        make $KERNEL_CMDLINE ${{ github.event.inputs.KERNEL_DEFCONFIG }} CC="ccache clang"
        make $KERNEL_CMDLINE CC="ccache clang" -j$(nproc --all)
        cp out/arch/arm64/boot/Image.gz AnyKernel3
        
    - name: Upload Kernel-SU
      uses: actions/upload-artifact@v3
      with:
        name: Qiuqiu-kernel-SU-${{ steps.get_time.outputs.TIME }}
        path: "AnyKernel3/*"
